[2023-02-02T13:24:15.686+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-04T00:00:00+00:00 [queued]>
[2023-02-02T13:24:15.768+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-04T00:00:00+00:00 [queued]>
[2023-02-02T13:24:15.772+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T13:24:15.772+0000] {taskinstance.py:1280} INFO - Starting attempt 6 of 6
[2023-02-02T13:24:15.774+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T13:24:15.925+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2021-11-04 00:00:00+00:00
[2023-02-02T13:24:16.029+0000] {standard_task_runner.py:55} INFO - Started process 13558 to run task
[2023-02-02T13:24:16.082+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v2', 'task1', 'backfill__2021-11-04T00:00:00+00:00', '--job-id', '1250', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp5zlfwndx']
[2023-02-02T13:24:16.106+0000] {standard_task_runner.py:83} INFO - Job 1250: Subtask task1
[2023-02-02T13:24:16.821+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-04T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T13:24:17.341+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v2
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2021-11-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-11-04T00:00:00+00:00
[2023-02-02T13:24:17.378+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T13:24:17.387+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T13:24:17.508+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T13:24:17.530+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T13:24:17.537+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T13:24:17.604+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T13:24:17.716+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_catchup_backfill_v2, task_id=task1, execution_date=20211104T000000, start_date=20230202T132415, end_date=20230202T132417
[2023-02-02T13:24:17.880+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1250 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 13558)
[2023-02-02T13:24:17.974+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T13:24:18.097+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
