[2023-02-02T12:57:21.835+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-06T00:00:00+00:00 [queued]>
[2023-02-02T12:57:21.933+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-06T00:00:00+00:00 [queued]>
[2023-02-02T12:57:21.935+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:57:21.937+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 6
[2023-02-02T12:57:21.938+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:57:22.058+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2021-11-06 00:00:00+00:00
[2023-02-02T12:57:22.090+0000] {standard_task_runner.py:55} INFO - Started process 12776 to run task
[2023-02-02T12:57:22.149+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v2', 'task1', 'backfill__2021-11-06T00:00:00+00:00', '--job-id', '1221', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpuch1wu90']
[2023-02-02T12:57:22.159+0000] {standard_task_runner.py:83} INFO - Job 1221: Subtask task1
[2023-02-02T12:57:22.676+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-06T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T12:57:23.455+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v2
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2021-11-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-11-06T00:00:00+00:00
[2023-02-02T12:57:23.469+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T12:57:23.472+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T12:57:23.548+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T12:57:23.570+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T12:57:23.593+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T12:57:23.701+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T12:57:23.713+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v2, task_id=task1, execution_date=20211106T000000, start_date=20230202T125721, end_date=20230202T125723
[2023-02-02T12:57:23.818+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1221 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 12776)
[2023-02-02T12:57:23.935+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T12:57:24.084+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
