[2023-02-02T11:06:40.571+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2023-02-02T11:06:40.874+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2023-02-02T11:06:40.887+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:06:40.889+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-02T11:06:40.890+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:06:41.131+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-08 00:00:00+00:00
[2023-02-02T11:06:41.201+0000] {standard_task_runner.py:55} INFO - Started process 8433 to run task
[2023-02-02T11:06:41.318+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-08T00:00:00+00:00', '--job-id', '1010', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmptv3ygzal']
[2023-02-02T11:06:41.330+0000] {standard_task_runner.py:83} INFO - Job 1010: Subtask task1
[2023-02-02T11:06:42.157+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-08T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T11:06:43.034+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-08T00:00:00+00:00
[2023-02-02T11:06:43.072+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T11:06:43.081+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T11:06:43.310+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T11:06:43.402+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T11:06:43.470+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T11:06:43.685+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T11:06:43.804+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221108T000000, start_date=20230202T110640, end_date=20230202T110643
[2023-02-02T11:06:44.001+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1010 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 8433)
[2023-02-02T11:06:44.214+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T11:06:45.010+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
