[2023-02-02T12:10:40.364+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2023-02-02T12:10:40.561+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2023-02-02T12:10:40.564+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:10:40.585+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 6
[2023-02-02T12:10:40.597+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:10:41.124+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-27 00:00:00+00:00
[2023-02-02T12:10:41.394+0000] {standard_task_runner.py:55} INFO - Started process 10331 to run task
[2023-02-02T12:10:41.577+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-27T00:00:00+00:00', '--job-id', '1144', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpnhmk90u9']
[2023-02-02T12:10:41.631+0000] {standard_task_runner.py:83} INFO - Job 1144: Subtask task1
[2023-02-02T12:10:42.274+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-27T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T12:10:43.473+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-27T00:00:00+00:00
[2023-02-02T12:10:43.540+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T12:10:43.548+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T12:10:43.729+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T12:10:43.776+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T12:10:43.786+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T12:10:43.860+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T12:10:43.944+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221127T000000, start_date=20230202T121040, end_date=20230202T121043
[2023-02-02T12:10:44.097+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1144 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 10331)
[2023-02-02T12:10:44.251+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T12:10:44.366+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
