[2023-02-02T12:21:43.566+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2023-02-02T12:21:43.727+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2023-02-02T12:21:43.744+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:21:43.746+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 6
[2023-02-02T12:21:43.747+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:21:43.954+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-27 00:00:00+00:00
[2023-02-02T12:21:44.017+0000] {standard_task_runner.py:55} INFO - Started process 10485 to run task
[2023-02-02T12:21:44.112+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-27T00:00:00+00:00', '--job-id', '1147', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpxsrtswva']
[2023-02-02T12:21:44.125+0000] {standard_task_runner.py:83} INFO - Job 1147: Subtask task1
[2023-02-02T12:21:45.692+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-27T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T12:21:47.255+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-27T00:00:00+00:00
[2023-02-02T12:21:47.313+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T12:21:47.338+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T12:21:47.695+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T12:21:47.734+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T12:21:47.747+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T12:21:47.914+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T12:21:48.005+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221127T000000, start_date=20230202T122143, end_date=20230202T122147
[2023-02-02T12:21:48.269+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1147 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 10485)
[2023-02-02T12:21:48.630+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T12:21:49.573+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
