[2023-02-02T11:06:41.821+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-15T00:00:00+00:00 [queued]>
[2023-02-02T11:06:41.949+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-15T00:00:00+00:00 [queued]>
[2023-02-02T11:06:41.970+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:06:41.972+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-02T11:06:41.973+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:06:42.122+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-15 00:00:00+00:00
[2023-02-02T11:06:42.162+0000] {standard_task_runner.py:55} INFO - Started process 8439 to run task
[2023-02-02T11:06:42.297+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-15T00:00:00+00:00', '--job-id', '1014', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpmhp_54_k']
[2023-02-02T11:06:42.319+0000] {standard_task_runner.py:83} INFO - Job 1014: Subtask task1
[2023-02-02T11:06:43.491+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-15T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T11:06:44.809+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-15T00:00:00+00:00
[2023-02-02T11:06:44.886+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T11:06:44.944+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T11:06:45.088+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T11:06:45.112+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T11:06:45.134+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T11:06:45.251+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T11:06:45.373+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221115T000000, start_date=20230202T110641, end_date=20230202T110645
[2023-02-02T11:06:45.555+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1014 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 8439)
[2023-02-02T11:06:45.815+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T11:06:46.766+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
