[2023-02-02T11:06:42.691+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-16T00:00:00+00:00 [queued]>
[2023-02-02T11:06:42.744+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-16T00:00:00+00:00 [queued]>
[2023-02-02T11:06:42.746+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:06:42.749+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-02T11:06:42.751+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:06:43.126+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-16 00:00:00+00:00
[2023-02-02T11:06:43.225+0000] {standard_task_runner.py:55} INFO - Started process 8444 to run task
[2023-02-02T11:06:43.318+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-16T00:00:00+00:00', '--job-id', '1016', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp2ljpl3ec']
[2023-02-02T11:06:43.334+0000] {standard_task_runner.py:83} INFO - Job 1016: Subtask task1
[2023-02-02T11:06:45.123+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-16T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T11:06:46.078+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-16T00:00:00+00:00
[2023-02-02T11:06:46.095+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T11:06:46.098+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T11:06:46.196+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T11:06:46.260+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T11:06:46.262+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T11:06:46.367+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T11:06:46.465+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221116T000000, start_date=20230202T110642, end_date=20230202T110646
[2023-02-02T11:06:46.575+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1016 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 8444)
[2023-02-02T11:06:46.763+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T11:06:46.994+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
