[2023-02-02T12:52:05.942+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-03T00:00:00+00:00 [queued]>
[2023-02-02T12:52:05.968+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-03T00:00:00+00:00 [queued]>
[2023-02-02T12:52:05.969+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:52:05.970+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 6
[2023-02-02T12:52:05.970+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:52:06.122+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2021-11-03 00:00:00+00:00
[2023-02-02T12:52:06.138+0000] {standard_task_runner.py:55} INFO - Started process 12437 to run task
[2023-02-02T12:52:06.155+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v2', 'task1', 'backfill__2021-11-03T00:00:00+00:00', '--job-id', '1212', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpx8g9puqy']
[2023-02-02T12:52:06.160+0000] {standard_task_runner.py:83} INFO - Job 1212: Subtask task1
[2023-02-02T12:52:06.486+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-03T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T12:52:06.810+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v2
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2021-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-11-03T00:00:00+00:00
[2023-02-02T12:52:06.814+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T12:52:06.823+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T12:52:06.876+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T12:52:06.910+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T12:52:06.914+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T12:52:06.945+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T12:52:06.969+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v2, task_id=task1, execution_date=20211103T000000, start_date=20230202T125205, end_date=20230202T125206
[2023-02-02T12:52:07.018+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1212 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 12437)
[2023-02-02T12:52:07.060+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T12:52:07.149+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
