[2023-02-02T11:35:11.934+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2023-02-02T11:35:12.412+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2023-02-02T11:35:12.432+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:35:12.441+0000] {taskinstance.py:1280} INFO - Starting attempt 6 of 6
[2023-02-02T11:35:12.445+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:35:12.787+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-03 00:00:00+00:00
[2023-02-02T11:35:13.005+0000] {standard_task_runner.py:55} INFO - Started process 9965 to run task
[2023-02-02T11:35:13.497+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-03T00:00:00+00:00', '--job-id', '1110', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp0_72t06m']
[2023-02-02T11:35:13.547+0000] {standard_task_runner.py:83} INFO - Job 1110: Subtask task1
[2023-02-02T11:35:16.163+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-03T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T11:35:17.374+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T00:00:00+00:00
[2023-02-02T11:35:17.389+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T11:35:17.392+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T11:35:17.769+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T11:35:17.816+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T11:35:17.854+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T11:35:18.078+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T11:35:18.151+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221103T000000, start_date=20230202T113512, end_date=20230202T113518
[2023-02-02T11:35:18.394+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1110 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 9965)
[2023-02-02T11:35:18.611+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T11:35:18.701+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
