[2023-02-02T13:24:14.342+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-02T00:00:00+00:00 [queued]>
[2023-02-02T13:24:14.482+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-02T00:00:00+00:00 [queued]>
[2023-02-02T13:24:14.483+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T13:24:14.486+0000] {taskinstance.py:1280} INFO - Starting attempt 6 of 6
[2023-02-02T13:24:14.489+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T13:24:14.727+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2021-11-02 00:00:00+00:00
[2023-02-02T13:24:14.778+0000] {standard_task_runner.py:55} INFO - Started process 13553 to run task
[2023-02-02T13:24:14.917+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v2', 'task1', 'backfill__2021-11-02T00:00:00+00:00', '--job-id', '1246', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp7fadgo8u']
[2023-02-02T13:24:14.920+0000] {standard_task_runner.py:83} INFO - Job 1246: Subtask task1
[2023-02-02T13:24:15.833+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v2.task1 backfill__2021-11-02T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T13:24:16.838+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v2
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2021-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-11-02T00:00:00+00:00
[2023-02-02T13:24:16.847+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T13:24:16.854+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T13:24:17.009+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T13:24:17.014+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T13:24:17.017+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T13:24:17.096+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T13:24:17.119+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_catchup_backfill_v2, task_id=task1, execution_date=20211102T000000, start_date=20230202T132414, end_date=20230202T132417
[2023-02-02T13:24:17.210+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1246 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 13553)
[2023-02-02T13:24:17.285+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T13:24:17.669+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
