[2023-02-02T11:18:43.028+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-06T00:00:00+00:00 [queued]>
[2023-02-02T11:18:54.837+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-06T00:00:00+00:00 [queued]>
[2023-02-02T11:18:54.971+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:18:55.022+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 6
[2023-02-02T11:18:55.033+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:19:09.969+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-06 00:00:00+00:00
[2023-02-02T11:19:13.509+0000] {standard_task_runner.py:55} INFO - Started process 8889 to run task
[2023-02-02T11:19:16.077+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-06T00:00:00+00:00', '--job-id', '1036', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpqi7wqmu6']
[2023-02-02T11:19:16.615+0000] {standard_task_runner.py:83} INFO - Job 1036: Subtask task1
[2023-02-02T11:19:31.783+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-06T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T11:19:33.835+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-06T00:00:00+00:00
[2023-02-02T11:19:33.860+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T11:19:33.883+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T11:19:34.105+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T11:19:34.228+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T11:19:34.241+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T11:19:34.325+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T11:19:34.625+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221106T000000, start_date=20230202T111844, end_date=20230202T111934
[2023-02-02T11:19:34.930+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1036 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 8889)
[2023-02-02T11:19:35.656+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T11:19:36.846+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
